#! /bin/sh
xrandr \
    --output DVI-I-1-1 --auto --left-of DVI-I-2-2 --rotate left  \
    --output DVI-I-2-2 --auto --above eDP-1 
i3-msg restart

pacmd unload-module module-udev-detect && pacmd load-module module-udev-detect
