#! /bin/sh
export DISPLAY=:0
export XAUTHORITY=/home/miklos/.Xauthority


HOME_MONITOR=$(xrandr | grep "DP1 connected")

if [[ $HOME_MONITOR ]]; then
    xrandr \
        --output DP1 --auto --scale 2 --above eDP1 
else
    xrandr \
        --output DP1 --off
fi

i3-msg restart

# pacmd unload-module module-udev-detect && pacmd load-module module-udev-detect
