#!/bin/bash
set -e

SCREEN=/tmp/screen.png
BLURRED=/tmp/lockscreen.png

# /usr/bin/flameshot full -r > $SCREEN
# /usr/bin/ffmpeg -y -i $SCREEN -filter_complex "boxblur=20:1" $BLURRED > /dev/null 2>&1
# /usr/bin/i3lock -i $BLURRED -u -e
swaylock -f -e \
    -c 000000 \
    --text-color ffffff \
    --ring-color 222222 \
    --indicator-radius 100 \
    --indicator-idle-visible

rm $SCREEN $BLURRED
