#! /bin/sh
xrandr --output DVI-I-1-1 --off
xrandr --output DVI-I-2-2 --off
xrandr --output HDMI-2 --off
i3-msg restart

# pacmd unload-module module-udev-detect && pacmd load-module module-udev-detect

