#! /bin/bash 

UPDATES=$(yay -Qu)

if [[ -z ${UPDATES} ]]; then
    dunstify -a "System" -u low -t 5000 "No updates for now."
else
    echo "Updates"
    dunstify -a "System" -t 5000 "Updates found!"
fi
